import tkinter as tk

window=tk.Tk()
window.title('Registration Page')
l1=tk.Label(window,text='Name:')
l1.grid(row=0,column=0)
l2=tk.Label(window,text='E-mail Id:')
l2.grid(row=1,column=0)
l3=tk.Label(window,text='Username:')
l3.grid(row=2,column=0)
l4=tk.Label(window,text='Password:')
l4.grid(row=3,column=0)
l5=tk.Label(window,text='Confirm Password:')
l5.grid(row=4,columnspan=2)
e1=tk.Entry(window)
e1.grid(row=0,column=2)
e2=tk.Entry(window)
e2.grid(row=1,column=2)
e3=tk.Entry(window)
e3.grid(row=2,column=2)
e4=tk.Entry(window)
e4.grid(row=3,column=2)
e5=tk.Entry(window)
e5.grid(row=4,column=2)
cb=tk.Checkbutton(window,text='I agree with the Terms.')
cb.grid(row=5,columnspan=2)
b=tk.Button(window,text='Sign Up')
b.grid(row=6,columnspan=4)
window.mainloop()


